import "../../globals.css"

export const metadata = {
    title: 'Product',
    description: 'Generated by create next app',
  }
  
  export default function BlogsLayout({
      children,
    }) {
      return <section>{children}</section>;
    }