import { Toaster } from "react-hot-toast"
import { StateContext } from "../../../../context/StateContext"
import "../../styles/globals.css"

export const metadata = {
  title: 'Success',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className="bg-black h-screen">
      <StateContext>
      <Toaster />
      {children}
      </StateContext>
      </body>
    </html>
  )
}