import { StateContext } from '../../context/StateContext'
import { Toaster } from 'react-hot-toast'
import { Footer, Navbar } from './components'
import "./styles/globals.css"
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Spense Store',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-w-[100vw] min-h-screen`} style={{backgroundImage: 'url(/header.png)' , backgroundSize: 'cover', backgroundRepeat: 'no-repeat', backgroundPosition: 'center', backgroundAttachment: 'fixed', backgroundColor: '#fff'}}>
      <StateContext>
      <Toaster />
      <div className='layout'>
      <header>
        <Navbar />
      </header>
      <main className="main-container pt-12">
      {children}
      </main>
      <footer>
        <Footer />
      </footer>
      </div>
      </StateContext>
      </body>
    </html>
  )
}
