import { Footer, Navbar } from './components'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Spense Store',
  description: 'Generated by create next app',
}

import "./globals.css"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <div className='layout'>

      <header>
        <Navbar />
      </header>
      <main className="main-container pt-12">
      {children}
      </main>
      <footer>
        <Footer />
      </footer>
      </div>
      </body>
    </html>
  )
}
