import "../../styles/globals.css"

export const metadata = {
    title: 'Product',
    description: 'Generated by create next app',
  }
  
  export default function BlogsLayout({
      children,
    }) {
      return <section className=" min-h-[50vh] bg-black rounded-2xl">{children}</section>;
    }