import { Toaster } from "react-hot-toast"
import { StateContext } from "../../../../context/StateContext"
import { Footer, Navbar } from "../../components"
import "../../styles/globals.css"

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body >
      <StateContext>
      <Toaster />
      <div className="min-h-screen bg-black flex flex-col">
        <Navbar />

        <section className="flex-1">
          {children}
        </section>

        <Footer />
      </div>
      </StateContext>
      </body>
    </html>
  )
}